# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    tags:
      - v1.*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - run: |
          sudo apt-get install -y fonts-noto
      - run: |
          npm i
          npm run build
      - run: |
          npm run configure
      - run: |
          git config pull.ff only
          git pull
          git add .
          git commit -m "generate PDF" -a
          git push origin main
